add verification
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

diff --git a/.github/workflows/modulimerge.yml b/.github/workflows/modulimerge.yml
--- a/.github/workflows/modulimerge.yml
+++ b/.github/workflows/modulimerge.yml
@@ -42,6 +42,15 @@ jobs:
           rm -v /tmp/moduli.tmp
           head -n5 ./moduli
 
+      - name: Verify moduli file
+        run: |
+          set -eu -o pipefail
+          grep -vE '^#|^$' moduli | shuf -n10 | ssh-keygen -M screen /tmp/mod.test
+          grep "$(shuf -n5 /tmp/mod.test | awk '{print $NF}')" moduli || {
+            echo "Moduli file verification failed"
+            exit 1
+          }
+
       - name: Upload moduli artifact
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
